# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: bootcamp

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
                  cmd: install
    - run: npm ci
    - run: yarn build
    - name: deploying on surge
      run: surge ./build http://remarkable-roof.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
